"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Download, Loader2 } from "lucide-react";
import type { ReceiptData } from "@/types";
import { formatAmount, formatAddress } from "@/lib/utils";

interface ReceiptDownloadProps {
  receipt: ReceiptData;
}

export function ReceiptDownload({ receipt }: ReceiptDownloadProps) {
  const [generating, setGenerating] = useState(false);

  const generatePDF = async () => {
    setGenerating(true);

    // Generate a clean HTML receipt and trigger download as PDF
    const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #f8fafc; color: #1e293b; padding: 40px; }
    .receipt { max-width: 480px; margin: 0 auto; background: white; border-radius: 16px; overflow: hidden; box-shadow: 0 4px 24px rgba(0,0,0,0.08); }
    .header { background: linear-gradient(135deg, #1a6bf5, #1355e1); color: white; padding: 32px; text-align: center; }
    .header h1 { font-size: 24px; margin-bottom: 8px; }
    .header .amount { font-size: 48px; font-weight: 700; margin: 16px 0; }
    .header .date { opacity: 0.7; font-size: 14px; }
    .body { padding: 32px; }
    .row { display: flex; justify-content: space-between; padding: 12px 0; border-bottom: 1px solid #f1f5f9; }
    .row:last-child { border-bottom: none; }
    .label { color: #64748b; font-size: 14px; }
    .value { font-size: 14px; font-weight: 500; text-align: right; max-width: 60%; word-break: break-all; }
    .footer { text-align: center; padding: 24px; color: #94a3b8; font-size: 12px; }
    .status { display: inline-block; padding: 4px 12px; border-radius: 20px; font-size: 12px; font-weight: 600; }
    .status.confirmed { background: #dcfce7; color: #166534; }
    .status.pending { background: #fef9c3; color: #854d0e; }
    .status.failed { background: #fee2e2; color: #991b1b; }
  </style>
</head>
<body>
  <div class="receipt">
    <div class="header">
      <h1>💧 Droplet Receipt</h1>
      <div class="amount">${formatAmount(receipt.amountMist)} SUI</div>
      <div class="date">${new Date(receipt.timestamp).toLocaleString()}</div>
    </div>
    <div class="body">
      <div class="row">
        <span class="label">Status</span>
        <span class="status ${receipt.status}">${receipt.status}</span>
      </div>
      <div class="row">
        <span class="label">From</span>
        <span class="value">${formatAddress(receipt.senderAddress, 6)}</span>
      </div>
      <div class="row">
        <span class="label">To</span>
        <span class="value">${receipt.recipientDisplayName || formatAddress(receipt.recipientAddress, 6)}</span>
      </div>
      <div class="row">
        <span class="label">Network</span>
        <span class="value">Sui Testnet</span>
      </div>
      <div class="row">
        <span class="label">Transaction</span>
        <span class="value">${formatAddress(receipt.txDigest, 8)}</span>
      </div>
    </div>
    <div class="footer">
      Verified on Sui Blockchain · Generated by Droplet
    </div>
  </div>
</body>
</html>`;

    // Create a blob and download
    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);

    // Open in new window for print-to-PDF
    const printWindow = window.open(url, "_blank");
    if (printWindow) {
      printWindow.onload = () => {
        printWindow.print();
        setTimeout(() => URL.revokeObjectURL(url), 1000);
      };
    }

    setGenerating(false);
  };

  return (
    <Button
      variant="outline"
      onClick={generatePDF}
      disabled={generating}
      className="flex-1"
    >
      {generating ? (
        <Loader2 className="mr-2 h-4 w-4 animate-spin" />
      ) : (
        <Download className="mr-2 h-4 w-4" />
      )}
      Download PDF
    </Button>
  );
}
